### ISSUE TITLE
새로 모델을 구성하기 때문에 weights안에 있는 파일들을 지우는게 좋지 않을까요?

### ISSUE THREAD

**Issue by qkrwjdduf159** [Proj-Caliber/Waste-Recycling-Image-Segmentation#23]
새로 모델을 구성하기 때문에 weights안에 있는 파일들을 지우는게 좋지 않을까요?

_Originally posted by @qkrwjdduf159 in https://github.com/Proj-Caliber/Waste-Recycling-Image-Segmentation/pull/22#r773867912_

**Comment by AshbeeKim** [comment]
👍🏼
